
%% Build the S-function

if isunix
    disp("Building S-function for Linux...")
    mex -R2018a -v...
        -output matlab_physics_model_sfcn...
        COMPFLAGS="$COMPFLAGS -std=c++17"...
        '-I_deps/msgpack/include'...
        '-I_deps/nng-install/include'...
        '-L_deps/nng-install/lib'...
        '-lnng'...
        '-DNNG_STATIC_LIB=ON'...
        'matlab_physics_model_sfcn.cpp'...
        'matlab_physics_model_wrapper.cpp'
elseif ispc
    disp("Building S-function for Win64...")
    mex -R2018a -v...
        -output matlab_physics_model_sfcn...
        COMPFLAGS="$COMPFLAGS /std:c++17"...
        '-I_deps/msgpack/include'...
        '-I_deps/nng-install/include'...
        '-L_deps/nng-install/lib'...
        '-lnng'...
        '-DNNG_STATIC_LIB=ON'...
        '-lws2_32'...
        '-lmswsock'...
        '-ladvapi32'...
        'matlab_physics_model_sfcn.cpp'...
        'matlab_physics_model_wrapper.cpp'
else
    disp('This platform not supported.')
end
