name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for main docs
        working-directory: ./docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies for Python client docs
        working-directory: ./client/python/projectairsim/docs
        run: |
          pip install -r requirements.txt

      - name: Build Python client docs
        working-directory: ./client/python/projectairsim/docs
        run: make html

      - name: Build main docs
        working-directory: ./docs
        run: make html

      - name: Copy Python client docs into main docs
        run: |
          mkdir -p docs/build/html/client_api
          cp -r client/python/projectairsim/docs/build/html/* docs/build/html/client_api/

      - name: Deploy to gh_page branch
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh_page
          force_orphan: true
